title: Hello World
author: A smol robot
email: github-tutorial@duwub.lol
description: > # this means to ignore newlines until "baseurl:"
  Just taking a tutorial to learn github sites.

# social links
twitter_username:  lolduwublol
github_username:  dUwUb

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
